# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 832cce61520fde478a8c2592abf515f958a296c10a86ccc6f0d0de4fb9787b2047fb7b4dc6b48362d17017c90cd57a5f084fd1a6a513e0a43f490c1263fa3f4a

test:
  secret_key_base: 0ef985e5da8669545e1dc1027ac4795409cfd468e64a72a4313a6a71da434bab8600839de697532823360e8b55f1151e999b99c3bac442abec0f8e6a686c0560

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
